version = 1
SPDX-PackageName = "vscode-mta-tools"
SPDX-PackageSupplier = "Raya Koren <raya.koren@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/SAP/vscode-mta-tools"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019-2021 SAP SE or an SAP affiliate company and vscode-mta-tools contributors"
SPDX-License-Identifier = "Apache-2.0"
