version: 2
jobs:
  build-node13:
    docker:
      - image: circleci/node:13-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm i
      - run: npm run ci

  build-node12:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm i
      - run: npm run ci

  build-node10:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm i
      - run: npm run ci

workflows:
  version: 2
  build:
    jobs:
      - build-node13
      - build-node12
      - build-node10
