version: 2
jobs:
  build-node13:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm i
      - run: npm run ci

  build-node12:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm i
      - run: npm run ci

  build-node10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm i
      - run: npm run ci

  deploy:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm i
      - run: npm run ci
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - build-node13
      - build-node12
      - build-node10
      - deploy:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
